# Generated by Django 4.2.4 on 2023-11-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blognews_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='description_small',
            field=models.TextField(default='', max_length=100, verbose_name='Description_small'),
        ),
    ]
