# Generated by Django 4.2.4 on 2023-11-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blognews_description_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='description_small',
            field=models.TextField(default='', max_length=400, verbose_name='Description_small'),
        ),
        migrations.AlterField(
            model_name='blognews',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publication Date'),
        ),
    ]
