# Generated by Django 4.2.4 on 2023-08-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='merchandise', verbose_name='Фотография')),
                ('size', models.CharField(max_length=20, verbose_name='Размер')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('is_main', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
