# Generated by Django 4.2.4 on 2023-08-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='color',
        ),
        migrations.RemoveField(
            model_name='services',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='services',
            name='size',
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
