# Generated by Django 4.2.4 on 2023-08-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_services_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recommended', verbose_name='photo')),
                ('is_main', models.BooleanField(default=False)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'recommended',
                'verbose_name_plural': 'recommended',
            },
        ),
    ]
