# Generated by Django 4.2.4 on 2023-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended',
            name='name',
            field=models.CharField(default=2, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
