# Generated by Django 4.2.4 on 2023-09-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommended',
            options={'verbose_name': 'Recommended', 'verbose_name_plural': 'Recommended'},
        ),
    ]
