# Generated by Django 4.2.4 on 2023-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_recommended_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Descriptions')),
                ('photo', models.ImageField(upload_to='project_photos/', verbose_name='Photo')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterField(
            model_name='recommended',
            name='image',
            field=models.ImageField(upload_to='recommended', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='recommended',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
