# Generated by Django 4.2.4 on 2023-09-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_project_options_remove_project_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='project',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='link_project',
            field=models.URLField(default='True'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
