# Generated by Django 4.2.4 on 2023-09-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_project_pub_date_project_is_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'Services_Slider',
                'verbose_name_plural': 'Services_Slider',
            },
        ),
    ]
