# Generated by Django 4.2.4 on 2023-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_servicesslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesslider',
            name='image',
            field=models.ImageField(upload_to='services-slider/', verbose_name='photo'),
        ),
    ]
