# Generated by Django 4.2.4 on 2023-09-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_servicesslider_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesslider',
            options={'verbose_name': 'Services-Slider', 'verbose_name_plural': 'Services-Slider'},
        ),
    ]
