# Generated by Django 4.2.4 on 2023-09-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_servicesslider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesslider',
            name='image',
            field=models.ImageField(upload_to='services-slider', verbose_name='photo'),
        ),
    ]
