# Generated by Django 4.2.4 on 2023-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_servicesslider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesslider',
            name='image',
            field=models.ImageField(upload_to='services_slider', verbose_name='photo'),
        ),
    ]
