# Generated by Django 4.2.4 on 2023-10-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_order_payment_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='assessment', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'Individual Assessment',
                'verbose_name_plural': 'Individual Assessment',
            },
        ),
    ]
