# Generated by Django 4.2.4 on 2023-10-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('advantages', models.TextField(verbose_name='Benefits')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('photo', models.ImageField(upload_to='disposal_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Disposal',
                'verbose_name_plural': 'Disposal',
            },
        ),
    ]
