# Generated by Django 4.2.4 on 2023-10-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_disposalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
    ]
