# Generated by Django 4.2.4 on 2023-10-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_disposalservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalservice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Discount'),
        ),
    ]
