# Generated by Django 4.2.4 on 2023-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_disposalservice_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disposal_photos/', verbose_name='Photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='disposalservice',
            name='photo',
        ),
        migrations.AddField(
            model_name='disposalservice',
            name='photos',
            field=models.ManyToManyField(blank=True, to='webapp.photo', verbose_name='Photos'),
        ),
    ]
