# Generated by Django 4.2.4 on 2023-10-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_photo_remove_disposalservice_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposalservice',
            name='photos',
        ),
        migrations.AddField(
            model_name='disposalservice',
            name='photo',
            field=models.ImageField(default=0, upload_to='disposal_photos/', verbose_name='Photo'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
