# Generated by Django 4.2.4 on 2023-10-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_remove_disposalservice_photos_disposalservice_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
    ]
