# Generated by Django 4.2.4 on 2023-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_drywall'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_month',
            field=models.IntegerField(default=1),
        ),
    ]
