# Generated by Django 4.2.4 on 2023-11-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
