# Generated by Django 4.2.4 on 2023-11-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_quality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name': 'Quality', 'verbose_name_plural': 'Quality'},
        ),
        migrations.AddField(
            model_name='quality',
            name='icon',
            field=models.CharField(default='fa fa-trophy', max_length=50),
        ),
    ]
