# Generated by Django 4.2.4 on 2023-11-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_backsplash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('advantages', models.TextField(verbose_name='Benefits')),
                ('material', models.CharField(max_length=150, verbose_name='Material')),
                ('photo', models.ImageField(default=0, upload_to='soundproofing_photos/', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Electrical',
                'verbose_name_plural': 'Electrical',
            },
        ),
        migrations.AlterField(
            model_name='backsplash',
            name='material',
            field=models.CharField(max_length=150, verbose_name='Material'),
        ),
    ]
