# Generated by Django 4.2.4 on 2023-11-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_electrical_alter_backsplash_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=0, upload_to='electrical_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Photo for Electrical',
                'verbose_name_plural': 'Photos for Electrical',
            },
        ),
        migrations.AlterField(
            model_name='electrical',
            name='material',
            field=models.CharField(max_length=350, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='electrical',
            name='photo',
            field=models.ImageField(default=0, upload_to='electrical_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='electricals', to='webapp.electricalphoto'),
        ),
    ]
