# Generated by Django 4.2.4 on 2023-11-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_rename_photo_electricalphoto_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricalphoto',
            old_name='photos',
            new_name='photo',
        ),
    ]
