# Generated by Django 4.2.4 on 2023-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_rename_photos_electricalphoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='electricalservice_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'ElectricalService',
                'verbose_name_plural': 'ElectricalService',
            },
        ),
    ]
