# Generated by Django 4.2.4 on 2023-11-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_handymanphoto_handymanservice_handyman'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=0, upload_to='painting_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Photo for Painting',
                'verbose_name_plural': 'Photos for Painting',
            },
        ),
        migrations.CreateModel(
            name='PaintingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='paintingservice_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'PaintingService',
                'verbose_name_plural': 'PaintingService',
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('advantages', models.TextField(verbose_name='Benefits')),
                ('material', models.CharField(max_length=350, verbose_name='Material')),
                ('photo', models.ImageField(default=0, upload_to='painting_photos/', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount')),
                ('photos', models.ManyToManyField(blank=True, related_name='painting', to='webapp.paintingphoto')),
            ],
            options={
                'verbose_name': 'Painting',
                'verbose_name_plural': 'Painting',
            },
        ),
    ]
