# Generated by Django 4.2.4 on 2023-11-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_paintingphoto_paintingservice_painting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurniturePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=0, upload_to='furniture_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Photo for Furniture',
                'verbose_name_plural': 'Photos for Furniture',
            },
        ),
        migrations.CreateModel(
            name='FurnitureService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='furnitureservice_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'FurnitureService',
                'verbose_name_plural': 'FurnitureService',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('advantages', models.TextField(verbose_name='Benefits')),
                ('material', models.CharField(max_length=350, verbose_name='Material')),
                ('photo', models.ImageField(default=0, upload_to='furniture_photos/', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount')),
                ('photos', models.ManyToManyField(blank=True, related_name='furniture', to='webapp.furniturephoto')),
            ],
            options={
                'verbose_name': 'Furniture',
                'verbose_name_plural': 'Furniture',
            },
        ),
    ]
