# Generated by Django 4.2.4 on 2023-11-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_furniturephoto_furnitureservice_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundproofingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=0, upload_to='soundproofing_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Photo for Soundproofing',
                'verbose_name_plural': 'Photos for Soundproofing',
            },
        ),
        migrations.CreateModel(
            name='SoundproofingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='soundproofingservice_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'SoundproofingService',
                'verbose_name_plural': 'SoundproofingService',
            },
        ),
        migrations.AlterField(
            model_name='soundproofing',
            name='material',
            field=models.CharField(max_length=350, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='soundproofing',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='soundproofing', to='webapp.soundproofingphoto'),
        ),
    ]
