# Generated by Django 4.2.4 on 2023-11-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_soundproofingphoto_soundproofingservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallpaperPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=0, upload_to='wallpaper_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Photo for Wallpaper',
                'verbose_name_plural': 'Photos for Wallpaper',
            },
        ),
        migrations.CreateModel(
            name='WallpaperService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='wallpaperservice_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'WallpaperService',
                'verbose_name_plural': 'WallpaperService',
            },
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('advantages', models.TextField(verbose_name='Benefits')),
                ('material', models.CharField(max_length=350, verbose_name='Material')),
                ('photo', models.ImageField(default=0, upload_to='wallpaper_photos/', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount')),
                ('photos', models.ManyToManyField(blank=True, related_name='wallpaper', to='webapp.wallpaperphoto')),
            ],
            options={
                'verbose_name': 'Wallpaper',
                'verbose_name_plural': 'Wallpaper',
            },
        ),
    ]
