# Generated by Django 4.2.4 on 2023-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_wallpaperphoto_wallpaperservice_wallpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrywallPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=0, upload_to='drywall_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Photo for Drywall',
                'verbose_name_plural': 'Photos for Drywall',
            },
        ),
        migrations.CreateModel(
            name='DrywallService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='drywallservice_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'DrywallService',
                'verbose_name_plural': 'DrywallService',
            },
        ),
        migrations.AlterField(
            model_name='drywall',
            name='material',
            field=models.CharField(max_length=350, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='drywall',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='soundproofing', to='webapp.drywallphoto'),
        ),
    ]
