# Generated by Django 4.2.4 on 2023-11-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_drywallphoto_drywallservice_alter_drywall_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=0, upload_to='disposal_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Photo for Disposal',
                'verbose_name_plural': 'Photos for Disposal',
            },
        ),
        migrations.AlterModelOptions(
            name='disposalservice',
            options={'verbose_name': 'DisposalService', 'verbose_name_plural': 'DisposalService'},
        ),
        migrations.RemoveField(
            model_name='disposalservice',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='disposalservice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='disposalservice',
            name='material',
        ),
        migrations.RemoveField(
            model_name='disposalservice',
            name='price',
        ),
        migrations.AlterField(
            model_name='disposalservice',
            name='photo',
            field=models.ImageField(upload_to='disposalservice_photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='drywall',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='drywall', to='webapp.drywallphoto'),
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('advantages', models.TextField(verbose_name='Benefits')),
                ('material', models.CharField(max_length=350, verbose_name='Material')),
                ('photo', models.ImageField(default=0, upload_to='disposal_photos/', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount')),
                ('photos', models.ManyToManyField(blank=True, related_name='disposal', to='webapp.disposalphoto')),
            ],
            options={
                'verbose_name': 'Disposal',
                'verbose_name_plural': 'Disposal',
            },
        ),
    ]
