# Generated by Django 4.2.4 on 2023-11-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_alter_news_options_alter_news_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
