# Generated by Django 4.2.4 on 2023-11-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
