# Generated by Django 4.2.4 on 2023-11-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0052_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='your@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='Your LastName', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='Your Password', max_length=128),
        ),
    ]
