# Generated by Django 4.2.4 on 2023-12-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0058_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos/'),
        ),
    ]
