# Generated by Django 4.2.4 on 2023-12-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0059_alter_photo_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo_User',
        ),
    ]
