# Generated by Django 4.2.4 on 2023-12-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0063_alter_user_photo_image_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='photo',
        ),
    ]
