# Generated by Django 4.2.4 on 2024-01-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0066_checkoutdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetails',
            name='user',
        ),
    ]
