# Generated by Django 4.2.4 on 2023-12-31 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0067_remove_payment_order_remove_transaction_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
