# Generated by Django 4.2.4 on 2024-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0068_rename_first_name_checkoutdetails_first_name_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price_check',
            field=models.IntegerField(max_length=100),
        ),
    ]
