# Generated by Django 4.2.4 on 2023-12-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0068_checkoutdetails_date_checkoutdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
