# Generated by Django 4.2.4 on 2024-03-18 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0069_alter_checkoutdetails_price_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price_check',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d{1,2})?$', 'Введите корректное числовое значение')]),
        ),
    ]
