# Generated by Django 4.2.4 on 2023-12-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0069_alter_checkoutdetails_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
