# Generated by Django 4.2.4 on 2024-03-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0070_alter_checkoutdetails_price_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price_check',
            field=models.CharField(max_length=100),
        ),
    ]
