# Generated by Django 4.2.4 on 2024-06-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0071_alter_checkoutdetails_price_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Review'},
        ),
    ]
