# Generated by Django 4.2.4 on 2023-12-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0071_alter_checkoutdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='date',
            field=models.DateField(),
        ),
    ]
