# Generated by Django 4.2.4 on 2024-01-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0072_alter_checkoutdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
