# Generated by Django 4.2.4 on 2024-08-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0072_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutdetails',
            options={'verbose_name': 'Checkout Details', 'verbose_name_plural': 'Checkout Details'},
        ),
    ]
