# Generated by Django 4.2.4 on 2024-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0073_alter_checkoutdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
