# Generated by Django 4.2.4 on 2024-01-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0073_alter_checkoutdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
