# Generated by Django 4.2.4 on 2024-08-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0074_checkoutdetails_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetails',
            name='name',
        ),
    ]
