# Generated by Django 4.2.4 on 2024-08-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0075_remove_checkoutdetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='additional_information',
            field=models.TextField(default='Additional Information', verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='brand',
            field=models.CharField(default='Brand', max_length=350, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='capacity',
            field=models.CharField(default='Capacity', max_length=350, verbose_name='Capacity'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='color',
            field=models.CharField(default='Color', max_length=350, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='description_all',
            field=models.TextField(default='description all', verbose_name='Description all'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='description_installations',
            field=models.TextField(default='description_installations', verbose_name='Description installations'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='material_up',
            field=models.CharField(default='Material Up', max_length=350, verbose_name='Material Up'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='power_source',
            field=models.CharField(default='Power Source', max_length=350, verbose_name='Power Source'),
        ),
        migrations.AddField(
            model_name='disposal',
            name='solution',
            field=models.TextField(default='Solution', verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price_check',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='description',
            field=models.TextField(default='Description', verbose_name='Description'),
        ),
    ]
