# Generated by Django 4.2.4 on 2024-10-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0076_disposal_additional_information_disposal_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeilingFanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=0, upload_to='ceiling_fan_photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Photo for Ceiling Fan',
                'verbose_name_plural': 'Photos for Ceiling Fans',
            },
        ),
        migrations.CreateModel(
            name='CeilingFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(default='Description', verbose_name='Description')),
                ('description_installations', models.TextField(default='Installation Instructions', verbose_name='Description of Installations')),
                ('description_all', models.TextField(default='Detailed Description', verbose_name='Description All')),
                ('additional_information', models.TextField(default='Additional Information', verbose_name='Additional Information')),
                ('solution', models.TextField(default='Solution', verbose_name='Solution')),
                ('advantages', models.TextField(verbose_name='Benefits')),
                ('brand', models.CharField(default='Brand', max_length=350, verbose_name='Brand')),
                ('capacity', models.CharField(default='Capacity', max_length=350, verbose_name='Capacity')),
                ('color', models.CharField(default='Color', max_length=350, verbose_name='Color')),
                ('material_up', models.CharField(default='Material Up', max_length=350, verbose_name='Material Up')),
                ('power_source', models.CharField(default='Power Source', max_length=350, verbose_name='Power Source')),
                ('material', models.CharField(max_length=350, verbose_name='Material')),
                ('photo', models.ImageField(default=0, upload_to='ceiling_fan_photos/', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount')),
                ('photos', models.ManyToManyField(blank=True, related_name='ceiling_fan', to='webapp.ceilingfanphoto')),
            ],
            options={
                'verbose_name': 'Ceiling Fan',
                'verbose_name_plural': 'Ceiling Fans',
            },
        ),
    ]
