# Generated by Django 4.2.4 on 2024-10-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0077_ceilingfanphoto_ceilingfan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceilingfan',
            name='capacity',
        ),
    ]
