# Generated by Django 4.2.4 on 2024-11-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0079_tvmountphoto_tvmount'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='product_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='product_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price_check',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
