# Generated by Django 4.2.4 on 2024-11-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0084_product_additional_description_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='discount_check',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
