# Generated by Django 4.2.4 on 2024-11-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0085_checkoutdetails_discount_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='name_check',
            field=models.CharField(default='', max_length=255),
        ),
    ]
