# Generated by Django 4.2.4 on 2024-11-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0087_alter_checkoutdetails_first_name_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetails',
            name='first_name_check',
        ),
    ]
