# Generated by Django 4.2.4 on 2024-12-02 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0089_checkoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='discount_check',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='last_name_check',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='order_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='price_check',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='town_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='user_email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
