# Generated by Django 4.2.4 on 2024-12-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0091_alter_checkoutdetails_product_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='product_object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
