# Generated by Django 4.2.4 on 2024-12-04 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0094_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='product_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
