# Generated by Django 4.2.4 on 2024-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0097_alter_checkoutdetails_product_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='product_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
