# Generated by Django 4.2.4 on 2024-12-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0098_alter_checkoutdetails_product_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='discount_check',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price_check',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
