# Generated by Django 4.2.4 on 2024-12-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0099_alter_checkoutdetails_discount_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='discount_check',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='price_check',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
