# Generated by Django 4.2.4 on 2024-12-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0100_alter_checkoutdetails_discount_check_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='product_content_type',
            new_name='product_content_type_id',
        ),
    ]
