# Generated by Django 4.2.4 on 2024-12-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0101_rename_product_content_type_checkoutdetails_product_content_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='product_content_type_id',
            new_name='product_content_type',
        ),
    ]
