# Generated by Django 4.2.4 on 2025-02-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0110_basket_basketitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flag_1',
            new_name='invoices',
        ),
    ]
