# Generated by Django 4.2.4 on 2025-02-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0111_rename_flag_1_product_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='webapp.category'),
        ),
    ]
