# Generated by Django 4.2.4 on 2025-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0112_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='invoice_description',
            field=models.TextField(blank=True, default='small job description'),
        ),
    ]
