# Generated by Django 4.2.4 on 2025-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0113_product_invoice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_createa_at',
            field=models.DecimalField(auto_created=True, blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
