# Generated by Django 4.2.4 on 2025-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0114_product_data_createa_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_createa_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
