# Generated by Django 4.2.4 on 2025-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0115_alter_product_data_createa_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data_createa_at',
        ),
        migrations.AddField(
            model_name='product',
            name='data_created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
