# Generated by Django 4.2.4 on 2025-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0116_remove_product_data_createa_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConsultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
