# Generated by Django 4.2.4 on 2025-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0117_orderconsultations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsultations',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
