# Generated by Django 4.2.4 on 2025-03-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0120_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
