# Generated by Django 4.2.4 on 2025-03-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0122_rename_phone_number_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='photo',
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webapp.order')),
            ],
        ),
    ]
