# Generated by Django 4.2.4 on 2025-03-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0123_remove_order_photo_orderphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип локации'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип проекта'),
        ),
        migrations.AddField(
            model_name='order',
            name='subcategories',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подкатегории'),
        ),
        migrations.AddField(
            model_name='order',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_description',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные детали о времени'),
        ),
        migrations.AddField(
            model_name='order',
            name='timeframe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сроки выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата визита'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время визита'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hours_needed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество часов'),
        ),
    ]
