# Generated by Django 4.2.4 on 2025-03-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0127_alter_order_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='project_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип проекта'),
        ),
    ]
